// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zeal.Bootcamp.DnD.Data;

#nullable disable

namespace Zeal.Bootcamp.DnD.Data.Migrations
{
    [DbContext(typeof(DnDContext))]
    [Migration("20260717015356_SqlServerSchema")]
    partial class SqlServerSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zeal.Bootcamp.DnD.Data.Entities.CharacterEntity", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BackgroundStory")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("EquippedWeaponItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CharacterId");

                    b.HasIndex("EquippedWeaponItemId");

                    b.ToTable("Character", (string)null);
                });

            modelBuilder.Entity("Zeal.Bootcamp.DnD.Data.Entities.ExperienceTrackerEntity", b =>
                {
                    b.Property<Guid>("ExperienceTrackerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("ExperienceTrackerId");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("ExperienceTracker", (string)null);
                });

            modelBuilder.Entity("Zeal.Bootcamp.DnD.Data.Entities.InventoryEntity", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InventoryId");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("Zeal.Bootcamp.DnD.Data.Entities.InventoryItemEntity", b =>
                {
                    b.Property<Guid>("InventoryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DamageDieSides")
                        .HasColumnType("int");

                    b.Property<int?>("DamageModifier")
                        .HasColumnType("int");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WeaponProficiency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("InventoryItemId");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryItem", (string)null);
                });

            modelBuilder.Entity("Zeal.Bootcamp.DnD.Data.Entities.CharacterEntity", b =>
                {
                    b.HasOne("Zeal.Bootcamp.DnD.Data.Entities.InventoryItemEntity", "EquippedWeaponItem")
                        .WithMany()
                        .HasForeignKey("EquippedWeaponItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EquippedWeaponItem");
                });

            modelBuilder.Entity("Zeal.Bootcamp.DnD.Data.Entities.ExperienceTrackerEntity", b =>
                {
                    b.HasOne("Zeal.Bootcamp.DnD.Data.Entities.CharacterEntity", "Character")
                        .WithOne("ExperienceTracker")
                        .HasForeignKey("Zeal.Bootcamp.DnD.Data.Entities.ExperienceTrackerEntity", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Zeal.Bootcamp.DnD.Data.Entities.InventoryEntity", b =>
                {
                    b.HasOne("Zeal.Bootcamp.DnD.Data.Entities.CharacterEntity", "Character")
                        .WithOne("Inventory")
                        .HasForeignKey("Zeal.Bootcamp.DnD.Data.Entities.InventoryEntity", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Zeal.Bootcamp.DnD.Data.Entities.InventoryItemEntity", b =>
                {
                    b.HasOne("Zeal.Bootcamp.DnD.Data.Entities.InventoryEntity", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Zeal.Bootcamp.DnD.Data.Entities.CharacterEntity", b =>
                {
                    b.Navigation("ExperienceTracker")
                        .IsRequired();

                    b.Navigation("Inventory")
                        .IsRequired();
                });

            modelBuilder.Entity("Zeal.Bootcamp.DnD.Data.Entities.InventoryEntity", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
